#!/bin/bash
# Generated by Claude VS Code Bridge
# Segments are toggled by the extension via comments

I=$(cat)

# JSON field extractor (pure bash — no jq/python)
jf() { echo "$I"|grep -o "\"$1\":\"[^\"]*\""|head -1|cut -d'"' -f4; }
jn() { echo "$I"|grep -o "\"$1\":[0-9.]*"|head -1|sed "s/.*://"|tr -d " "; }
jnested() { echo "$I"|grep -o "\"$1\":{[^}]*\"$2\":[0-9.]*"|head -1|sed "s/.*\"$2\"://"|tr -d " "; }

# ANSI colors
BD="\033[1m";DM="\033[2m";CN="\033[36m";GR="\033[32m";YL="\033[33m";RD="\033[31m";RS="\033[0m"

PARTS=()

#SEGMENT:model:BEGIN
M=$(jf display_name)
M=$(echo "$M"|sed "s/ (.*//")
[ -n "$M" ] && PARTS+=("${BD}${M}${RS}")
#SEGMENT:model:END

#SEGMENT:gitBranch:BEGIN
CWD=$(jf cwd)
B=$(git -C "${CWD:-.}" branch --show-current 2>/dev/null)
[ -n "$B" ] && [ ${#B} -gt 20 ] && B="${B:0:17}..."
[ -n "$B" ] && PARTS+=("${CN}${B}${RS}")
#SEGMENT:gitBranch:END

#SEGMENT:contextBar:BEGIN
P=$(jn used_percentage)
P=${P%%.*}
[ -z "$P" ] && P=0
F=$((P/10));BAR="";i=0
while [ $i -lt $F ];do BAR="${BAR}█";i=$((i+1));done
while [ $i -lt 10 ];do BAR="${BAR}░";i=$((i+1));done
[ "$P" -lt 70 ] && CC="$GR" || { [ "$P" -lt 90 ] && CC="$YL" || CC="$RD"; }
#SEGMENT:contextPercentage:YES
PARTS+=("${CC}${BAR}${RS} ${DM}${P}%${RS}")
#SEGMENT:contextPercentage:NO
#PARTS+=("${CC}${BAR}${RS}")
#SEGMENT:contextPercentage:ENDALT
#SEGMENT:contextBar:END

#SEGMENT:cost:BEGIN
COST=$(jn total_cost_usd)
[ -n "$COST" ] && [ "$COST" != "0" ] && PARTS+=("${DM}\$${COST}${RS}")
#SEGMENT:cost:END

#SEGMENT:linesChanged:BEGIN
LA=$(jn total_lines_added)
LR=$(jn total_lines_removed)
[ -n "$LA" ] && [ "$LA" != "0" -o "$LR" != "0" ] && PARTS+=("${DM}+${LA:-0}/-${LR:-0}${RS}")
#SEGMENT:linesChanged:END

#SEGMENT:rateLimits:BEGIN
R5=$(jnested five_hour used_percentage)
R5=${R5%%.*}
R7=$(jnested seven_day used_percentage)
R7=${R7%%.*}
RL=""
[ -n "$R5" ] && [ "$R5" != "0" ] && RL="5h:${R5}%"
[ -n "$R7" ] && [ "$R7" != "0" ] && RL="${RL:+$RL }7d:${R7}%"
[ -n "$RL" ] && PARTS+=("${DM}${RL}${RS}")
#SEGMENT:rateLimits:END

#SEGMENT:sessionDuration:BEGIN
DUR=$(jn total_duration_ms)
if [ -n "$DUR" ] && [ "$DUR" != "0" ]; then
  SECS=$((${DUR%%.*}/1000))
  if [ "$SECS" -ge 3600 ]; then
    PARTS+=("${DM}$((SECS/3600))h $((SECS%3600/60))m${RS}")
  elif [ "$SECS" -ge 60 ]; then
    PARTS+=("${DM}$((SECS/60))m${RS}")
  fi
fi
#SEGMENT:sessionDuration:END

#SEGMENT:selection:BEGIN
SF="$HOME/.claude-vscode-statusline.txt"
[ -f "$SF" ] && PARTS+=("$(cat "$SF")")
#SEGMENT:selection:END

# Join with separator and print
IFS=" · "
printf "%b\n" "${PARTS[*]}"
