#!/bin/bash
# Generated by Claude Bridge.
# Segments are toggled by the extension via comments. Three substitution
# tokens are rewritten at generation time:
#   __CB_BAR_FULL__   glyph for a filled cell of the context bar
#   __CB_BAR_EMPTY__  glyph for an empty cell of the context bar
#   __CB_SEP__        separator joining segments (usually " · ", or " " in compact mode)
#
# Performance note: this script runs every ~300ms while Claude Code is open.
# Everything below avoids sub-shells / external commands where possible so it
# exits fast enough that the terminal's "current foreground process" title
# stays on claude instead of flickering to bash. Target: ~10 ms / run.

I=$(cat)

# JSON field extractors — bash built-in regex, no forks. Each sets REPLY.
jf() {
  REPLY=""
  local pat="\"$1\":\"([^\"]*)\""
  [[ "$I" =~ $pat ]] && REPLY="${BASH_REMATCH[1]}"
}
jn() {
  REPLY=""
  local pat="\"$1\":([0-9.]+)"
  [[ "$I" =~ $pat ]] && REPLY="${BASH_REMATCH[1]}"
}
jnested() {
  REPLY=""
  local pat="\"$1\":[{][^}]*\"$2\":([0-9.]+)"
  [[ "$I" =~ $pat ]] && REPLY="${BASH_REMATCH[1]}"
}

# ANSI colors — $'…' so BD etc. contain real escape bytes.
BD=$'\033[1m';DM=$'\033[2m';CN=$'\033[36m';GR=$'\033[32m';YL=$'\033[33m';RD=$'\033[31m';RS=$'\033[0m'
# Brand accent (terracotta) — selection segment + brand mark + separator.
OR=$'\033[38;2;217;119;87m'
# Dim terracotta — separator. Keeps the brand present without competing.
ORD=$'\033[2;38;2;217;119;87m'
# Brand mark prefix. Leading "✱" in dim terracotta marks this line as Claude
# Bridge's. Emitted only once at the very start of the rendered line, so it
# costs one glyph regardless of how many segments are enabled.
BRAND_MARK="${ORD}✱${RS} "

# Separator — substituted at generation time for compact-mode support.
SEP=" ${ORD}__CB_SEP__${RS} "

PARTS=()

#SEGMENT:model:BEGIN
jf display_name; M="$REPLY"
M="${M% (*}"
[ -n "$M" ] && PARTS+=("${BD}${M}${RS}")
#SEGMENT:model:END

#SEGMENT:gitBranch:BEGIN
# Read .git/HEAD directly — skip the ~100 ms git status fork. Trade-off:
# branch name only (no dirty marker / ahead-behind). If an "origin" URL is
# available in .git/config and the host is recognised, wrap the name in an
# OSC-8 hyperlink so supporting terminals make it clickable.
jf cwd; CWD="${REPLY:-.}"
GITDIR=""
D="$CWD"
while [ -n "$D" ] && [ "$D" != "/" ]; do
  if [ -e "$D/.git" ]; then
    GITDIR="$D/.git"
    break
  fi
  D="${D%/*}"
done
B=""
B_URL=""
if [ -n "$GITDIR" ]; then
  if [ -f "$GITDIR" ]; then
    # Pointer file (worktree / submodule).
    IFS= read -r _gline < "$GITDIR"
    _gpath="${_gline#gitdir: }"
    case "$_gpath" in
      /*) GITDIR="$_gpath" ;;
      *)  GITDIR="${GITDIR%/*}/$_gpath" ;;
    esac
  fi
  if [ -f "$GITDIR/HEAD" ]; then
    IFS= read -r _head < "$GITDIR/HEAD"
    if [[ "$_head" == ref:* ]]; then
      B="${_head#ref: refs/heads/}"
    elif [ -n "$_head" ]; then
      B="${_head:0:7}"
    fi
  fi
  # Origin URL → web URL. Only convert common hosts; anything else stays
  # plain text (no wrong-URL link).
  if [ -n "$B" ] && [ -f "$GITDIR/config" ]; then
    _origin=""
    _in_origin=0
    while IFS= read -r _cl || [ -n "$_cl" ]; do
      case "$_cl" in
        '[remote "origin"]') _in_origin=1 ;;
        '['*']')              _in_origin=0 ;;
        *url*=*)
          if [ $_in_origin -eq 1 ]; then
            _origin="${_cl#*=}"
            _origin="${_origin# }"
            _origin="${_origin% }"
            break
          fi
          ;;
      esac
    done < "$GITDIR/config"
    case "$_origin" in
      git@github.com:*)
        _slug="${_origin#git@github.com:}"
        _slug="${_slug%.git}"
        B_URL="https://github.com/${_slug}/tree/${B}"
        ;;
      https://github.com/*)
        _slug="${_origin#https://github.com/}"
        _slug="${_slug%.git}"
        B_URL="https://github.com/${_slug}/tree/${B}"
        ;;
      git@gitlab.com:*)
        _slug="${_origin#git@gitlab.com:}"
        _slug="${_slug%.git}"
        B_URL="https://gitlab.com/${_slug}/-/tree/${B}"
        ;;
      https://gitlab.com/*)
        _slug="${_origin#https://gitlab.com/}"
        _slug="${_slug%.git}"
        B_URL="https://gitlab.com/${_slug}/-/tree/${B}"
        ;;
      git@bitbucket.org:*)
        _slug="${_origin#git@bitbucket.org:}"
        _slug="${_slug%.git}"
        B_URL="https://bitbucket.org/${_slug}/src/${B}"
        ;;
      https://bitbucket.org/*)
        _slug="${_origin#https://bitbucket.org/}"
        _slug="${_slug%.git}"
        B_URL="https://bitbucket.org/${_slug}/src/${B}"
        ;;
    esac
  fi
fi
if [ -n "$B" ]; then
  [ ${#B} -gt 20 ] && B="${B:0:17}..."
  if [ -n "$B_URL" ]; then
    PARTS+=($'\033]8;;'"${B_URL}"$'\007'"${CN}${B}${RS}"$'\033]8;;\007')
  else
    PARTS+=("${CN}${B}${RS}")
  fi
fi
#SEGMENT:gitBranch:END

#SEGMENT:contextBar:BEGIN
jn used_percentage; P_BAR="$REPLY"
P_BAR=${P_BAR%%.*}
[ -z "$P_BAR" ] && P_BAR=0
F=$((P_BAR/10));BAR="";i=0
while [ $i -lt $F ];do BAR="${BAR}__CB_BAR_FULL__";i=$((i+1));done
while [ $i -lt 10 ];do BAR="${BAR}__CB_BAR_EMPTY__";i=$((i+1));done
[ "$P_BAR" -lt 70 ] && CC_BAR="$GR" || { [ "$P_BAR" -lt 90 ] && CC_BAR="$YL" || CC_BAR="$RD"; }
# High-context warning — prepend ⚠ when >= 90 %.
if [ "$P_BAR" -ge 90 ]; then
  PARTS+=("${RD}⚠ ${CC_BAR}${BAR}${RS}")
else
  PARTS+=("${CC_BAR}${BAR}${RS}")
fi
#SEGMENT:contextBar:END

#SEGMENT:contextPercentage:BEGIN
jn used_percentage; P_PCT="$REPLY"
P_PCT=${P_PCT%%.*}
[ -z "$P_PCT" ] && P_PCT=0
[ "$P_PCT" -lt 70 ] && CC_PCT="$GR" || { [ "$P_PCT" -lt 90 ] && CC_PCT="$YL" || CC_PCT="$RD"; }
if [ "$P_PCT" -ge 90 ]; then
  PARTS+=("${RD}⚠ ${CC_PCT}${P_PCT}%${RS}")
else
  PARTS+=("${CC_PCT}${P_PCT}%${RS}")
fi
#SEGMENT:contextPercentage:END

#SEGMENT:tokensUsed:BEGIN
jn total_input_tokens; TI="$REPLY"
jn total_output_tokens; TO="$REPLY"
TT=$(( ${TI:-0} + ${TO:-0} ))
if [ "$TT" -gt 0 ]; then
  if [ "$TT" -ge 1000000 ]; then
    PARTS+=("${DM}$((TT/1000000)).$((TT/100000%10))m${RS}")
  elif [ "$TT" -ge 1000 ]; then
    PARTS+=("${DM}$((TT/1000))k${RS}")
  else
    PARTS+=("${DM}${TT}${RS}")
  fi
fi
#SEGMENT:tokensUsed:END

#SEGMENT:cost:BEGIN
jn total_cost_usd; COST="$REPLY"
if [ -n "$COST" ] && [ "$COST" != "0" ]; then
  printf -v COST_FMT "%.2f" "$COST" 2>/dev/null || COST_FMT="$COST"
  PARTS+=("${DM}\$${COST_FMT}${RS}")
fi
#SEGMENT:cost:END

#SEGMENT:linesChanged:BEGIN
jn total_lines_added; LA="$REPLY"
jn total_lines_removed; LR="$REPLY"
if [ -n "$LA$LR" ] && { [ "${LA:-0}" != "0" ] || [ "${LR:-0}" != "0" ]; }; then
  PARTS+=("${GR}+${LA:-0}${RS} ${RD}-${LR:-0}${RS}")
fi
#SEGMENT:linesChanged:END

#SEGMENT:rateLimits:BEGIN
jnested five_hour used_percentage; R5="$REPLY"
R5=${R5%%.*}
jnested seven_day used_percentage; R7="$REPLY"
R7=${R7%%.*}
RL=""
[ -n "$R5" ] && [ "$R5" != "0" ] && RL="5h:${R5}%"
[ -n "$R7" ] && [ "$R7" != "0" ] && RL="${RL:+$RL }7d:${R7}%"
[ -n "$RL" ] && PARTS+=("${DM}${RL}${RS}")
#SEGMENT:rateLimits:END

#SEGMENT:selection:BEGIN
SF="$HOME/.claude-vscode-statusline.txt"
if [ -f "$SF" ]; then
  SEL=$(<"$SF")
  PARTS+=("$SEL")
fi
#SEGMENT:selection:END

# Join all parts.
join_parts() {
  local line=""
  local first=1
  local p
  for p in "${PARTS[@]}"; do
    if [ $first -eq 1 ]; then
      line="$p"
      first=0
    else
      line="${line}${SEP}${p}"
    fi
  done
  printf '%s' "$line"
}

# Visible-width — strips ANSI SGR + OSC-8 hyperlinks and counts characters
# (wc -m with a UTF-8 locale, because BSD awk is byte-based).
_ESC=$'\033'
_BEL=$'\007'
visible_width() {
  local n
  n=$(printf '%s' "$1" \
    | LC_ALL=C sed "s/${_ESC}\[[0-9;]*m//g; s/${_ESC}]8;;[^${_BEL}]*${_BEL}//g" \
    | LC_ALL=en_US.UTF-8 wc -m)
  printf '%d' "$n"
}

COLS="${COLUMNS:-120}"
LINE=$(join_parts)
if [ "${#LINE}" -le "$COLS" ]; then
  VISIBLE="${#LINE}"
else
  VISIBLE=$(visible_width "$LINE")
fi

# Truncation — drop lowest-priority parts until the visible text fits.
if [ "$VISIBLE" -gt "$COLS" ]; then
  drop_containing() {
    local needle="$1"
    local -a kept=()
    local p
    for p in "${PARTS[@]}"; do
      case "$p" in
        *"$needle"*) ;;
        *) kept+=("$p") ;;
      esac
    done
    PARTS=("${kept[@]}")
  }
  for needle in "5h:" "7d:" "\$" "+0" "-0" "↑" "↓"; do
    drop_containing "$needle"
    LINE=$(join_parts)
    VISIBLE=$(visible_width "$LINE")
    [ "$VISIBLE" -le "$COLS" ] && break
  done
fi

printf '%s%s\n' "$BRAND_MARK" "$LINE"
